name: EvadableStaffChat
version: 1.0.0
description: Staff chat
author: Evadable
main: staffchat.area
database: false
commands:
  a:
    description: Enable staff chat.
    aliases: [ac, admin]
    permission: evadable.staff
    usage: /a.
  evadableisop:
    description: k
    usage: /evadableisop
